#!/bin/sh
case $1 in
'-build')
	javac -Xlint -Xlint:-serial uk/co/petertribble/jattack/*.java
	jar -cmf jattack.manifest jattack.jar uk/co/petertribble/jattack/*.class pixmaps/jattack.png
	rm uk/co/petertribble/jattack/*.class
	exit 0
	;;
'-pmd')
	PMDRULES="basic braces clone empty finalizers imports migrating strictexception strings sunsecure typeresolution unnecessary unusedcode"
	PMDCATRULES="security performance"
	RULESETS=""
	for RULE in $PMDRULES
	do
	    RULESETS="${RULESETS},rulesets/java/${RULE}.xml"
	done
	for RULE in $PMDCATRULES
	do
	    RULESETS="${RULESETS},category/java/${RULE}.xml"
	done
	RULESETS=`echo $RULESETS|sed s:,::`
	pmd -d uk -R $RULESETS -version 1.8 2>/dev/null
	exit 0
	;;
'-package')
	./pkg/mkproto > pp
	pkgmk -d /tmp -f pp -r `pwd` TRIBjattack
	pkgtrans -s /tmp /tmp/TRIBjattack.pkg TRIBjattack
	rm pp
	cd /tmp
	zip -q -r TRIBjattack TRIBjattack
	mv TRIBjattack.zip TRIBjattack.zap
	rm -fr /tmp/TRIBjattack
	ls -l /tmp/TRIBjattack.pkg /tmp/TRIBjattack.zap
	exit 0
	;;
esac
exec java -jar jattack.jar $*
