#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# Copyright 2025 Peter Tribble
#

PMDCACHE="${HOME}/.pmd/cache.jattack"

case $1 in
build)
	javac -Xlint uk/co/petertribble/jattack/*.java
	jar -cmf jattack.manifest jattack.jar uk/co/petertribble/jattack/*.class pixmaps/jattack.png
	rm uk/co/petertribble/jattack/*.class
	exit 0
	;;
javadoc)
	rm -fr javadoc
	mkdir javadoc
	javadoc -Xdoclint:all -d javadoc uk.co.petertribble.jattack
	exit 0
	;;
pmd)
	PMDCATRULES="security bestpractices performance multithreading"
	RULESETS="rulesets/java/quickstart.xml"
	shift
	for RULE in $PMDCATRULES "$@"
	do
	    RULESETS="${RULESETS},category/java/${RULE}.xml"
	done
	if [ ! -d "${HOME}/.pmd" ]; then
	    mkdir -p "${HOME}/.pmd"
	fi
	pmd check --cache "${PMDCACHE}" -d uk -R "$RULESETS" --use-version java-1.8 2>/dev/null
	exit 0
	;;
package)
	./pkg/mkproto > pp
	pkgmk -d /tmp -f pp -r $(pwd) TRIBjattack
	pkgtrans -s /tmp /tmp/TRIBjattack.pkg TRIBjattack
	rm pp
	rm -fr /tmp/TRIBjattack
	ls -l /tmp/TRIBjattack.pkg
	exit 0
	;;
esac
exec java -jar jattack.jar "$@"
